---
title: "Visualizations"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ds_cgm_complete <- read.csv("../data/ds_cgm_complete.csv")
```

```{r}
ds_cgm_complete %>%
  ggplot(aes(x = device_dt_tm_days_from_enroll, 
             y = glucose_value, 
             color = trt_group)) + 
  geom_jitter()
```

```{r}
ds_cgm_complete %>%
  group_by(pt_id, trt_group, visitnum) %>%
  summarise(mean_glucose_value = mean(glucose_value)) %>%
  ggplot(aes(x = visitnum, y = mean_glucose_value, color = trt_group)) + 
  geom_jitter()

ds_cgm_complete %>%
  group_by(pt_id, trt_group, device_dt_tm_days_from_enroll) %>%
  summarise(mean_glucose_value = mean(glucose_value)) %>%
  ggplot(aes(x = device_dt_tm_days_from_enroll, 
             y = mean_glucose_value, 
             color = trt_group,
             group = pt_id)) + 
  geom_line() + 
  facet_grid(trt_group ~ .)
```

```{r}
ds_cgm_complete %>%
  group_by(trt_group, device_dt_tm_days_from_enroll) %>%
  summarise(mean_glucose_value = mean(glucose_value),
            sd_glucose_value = sd(glucose_value)) %>%
  ggplot(aes(x = device_dt_tm_days_from_enroll, 
             y = mean_glucose_value, 
             color = trt_group,
             group = trt_group)) + 
  geom_line() + 
  geom_errorbar(aes(ymin = mean_glucose_value - sd_glucose_value,
                    ymax = mean_glucose_value + sd_glucose_value)) +
  facet_grid(trt_group ~ .)
```

```{r}
ds_cgm_complete %>%
  group_by(trt_group, visitnum) %>%
  summarise(mean_glucose_value = mean(glucose_value),
            sd_glucose_value = sd(glucose_value)) %>%
  ggplot(aes(x = visitnum, 
             y = mean_glucose_value, 
             color = trt_group,
             group = trt_group)) + 
  geom_line() + 
  geom_errorbar(aes(ymin = mean_glucose_value - sd_glucose_value,
                    ymax = mean_glucose_value + sd_glucose_value)) +
  facet_grid(trt_group ~ .)
```

cgm - both

```{r}
ds_cgm_complete %>%
  group_by(trt_group, device_dt_tm_days_from_enroll) %>%
  summarise(mean_glucose_value = mean(glucose_value),
            sd_glucose_value = sd(glucose_value)) %>%
  spread(key = )


  ggplot(aes(x = visitnum, 
             y = mean_glucose_value, 
             color = trt_group,
             group = trt_group)) + 
  geom_line() + 
  geom_errorbar(aes(ymin = mean_glucose_value - sd_glucose_value,
                    ymax = mean_glucose_value + sd_glucose_value)) +
  facet_grid(trt_group ~ .)
```




